server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/project_crowd

    username: root

    password: chen123
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: com.cl.user.pojo